[package]
name = "texture_playground"
version = "0.1.0"
authors = ["Paul Page <pjpage98@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["ttf"]
